flowchart LR
    X --> MG["MatchingGraph (mg)"]
    X[X: ArrayLike] --> |Optional| P[preprocessing]
    P --> MG
    Z --> MG
    Z[z: ArrayLike] --> |Optional| P
    MG --> SE[mg.set_edges]
    SE --> |Optional| FE[mg.filter_edges]
    SE --> |Optional| FN[mg.filter_nodes]
    SE --> |Optional| FG[mg.filter_subgraphs]

    SE --> MGM[mg.match]
    FE --> MGM
    FN --> MGM
    FG --> MGM
